### ISSUE TITLE
The specified value 'E-Mail Address' is not a valid email address.

### ISSUE THREAD

**Issue by muslimcentral** [kraftbj/genesis-enews-extended#117] opened 2015-06-24 05:46 UTC
If I set the feedburner ID, I get this html error:

<label for="subbox" class="screenread">E-Mail Address</label><input type="email" value="E-Mail Address" id="subbox" onfocus="if ( this.value == 'E-Mail Address') { this.value = ''; }" onblur="if ( this.value == '' ) { this.value = 'E-Mail Address'; }" name="email" required="required" />

**Comment by kraftbj** [comment] 2015-06-24 15:24
Hi @muslimcentral,

Could you send some additional information? I haven't been able to duplicate.

**Comment by muslimcentral** [comment] 2015-06-25 06:28
I installed the plugin, and ONLY set the feedburner ID and saved.

http://www.muslimcentralaudio.com/ - bottom of page, inspect page.

**Comment by kraftbj** [comment] 2015-06-25 16:06
The form works for me. Could you include a screenshot?

Depending on where the e-mail invalid error is coming from, it could either be from the browser checking the validity of an e-mail address and it is a browser bug or from Feedburner and it's a feedburner bug.

eNews Extended itself does not validate the e-mail addresses.

**Comment by muslimcentral** [comment] 2015-06-28 18:13
*As-Salamu `Alaykum | Peace be upon you*


 [image: Inline image 1]

*Kind Regards*
*Founder of Muslim Central*

*Websites - *Muslim Central Audio <http://www.muslimcentralaudio.com/> / Muslim
Central Tube <http:/www.muslimcentraltube.com>

*Mobile - *Google Android Play-store
<https://play.google.com/store/apps/developer?id=Muslim+Central+Media> / Apple
iTunes Store
<https://itunes.apple.com/us/artist/muslim-central/id883786390?mt=2> / Apple
App Store <https://itunes.apple.com/artist/nathmie-slamang/id996133013>
/ Amazon
App Store
<http://www.amazon.com/s/ref=bl_sr_mobile-apps?_encoding=UTF8&field-brandtextbin=Muslim%20Central&node=2350149011>
*Follow Us - *Facebook <http://www.facebook.com/MuslimCentral> / Twitter
<http://www.Twitter.com/MuslimCentral> / YouTube
<https://www.youtube.com/c/muslimcentral> / Email Subscription
<http://feeds.feedburner.com/MuslimCentral> (Muslim Central Audio)

**Comment by kraftbj** [comment] 2015-06-29 15:09
That's due to the type of placeholder used now, an older method that is slated to be fixed up. It actually isn't a functional problem and wouldn't prevent anyone from using the form. Closing this as a duplicate of #106.

**Closed by kraftbj** 2015-06-29 15:09 UTC
